#!/usr/bin/env bash
# This script install nginx server on ubuntu 16.04
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
rm  /var/www/html/index.nginx-debian.html
echo Holberton School > /var/www/html/index.html
