#!/usr/bin/env bash
# This script install nginx server on ubuntu 16.04
apt-get -y update
apt-get -y install nginx
echo Holberton School > /var/www/html/index.html
redir_page="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sed -i "48i\ $redir_page" /etc/nginx/sites-available/default
sed -i "48i\ $redir_page" /etc/nginx/sites-enabled/default
service nginx start
