#!/usr/bin/env bash
# This script install nginx server on ubuntu 16.04
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo Holberton School > /var/www/html/index.html
redir_page="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.google.com;\n\t}\n"
sudo sed -i "48i\ $redir_page" /etc/nginx/sites-available/default
sudo sed -i "48i\ $redir_page" /etc/nginx/sites-enabled/default
service nginx start
