#!/usr/bin/env bash
# This script install nginx server on ubuntu 16.04 and configure redirect and error page 404
apt-get -y update
apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
redir_page="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "48i\ $redir_page" /etc/nginx/sites-available/default
sudo sed -i "48i\ $redir_page" /etc/nginx/sites-enabled/default
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
page_404="\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "47i\ $page_404" /etc/nginx/sites-available/default
sudo sed -i "47i\ $page_404" /etc/nginx/sites-enabled/default
service nginx reload
