#!/usr/bin/env bash
# This script install nginx server on ubuntu 16.04
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mv  /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.old
echo Holberton School > /var/www/html/index.html
