#!/usr/bin/env bash
# This script that displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then Hi on a new line.
i=1
while [ $i -le 10 ]
do
	if [ $i -ne 9 ]
	then
		echo "Holberton School"
	else
		echo "Hi"
	fi
	i=$((i + 1))
done
