#!/usr/bin/env bash
# change localhosts for 127.0.0.2 and add facebook 8.8.8.8 
cp /etc/hosts ~/host_file
sed -i s/127.0.0.1/127.0.0.2/ ~/host_file
echo '8.8.8.8	facebook.com' >> ~/host_file
cp -f ~/host_file /etc/hosts
