#!/usr/bin/env bash
sudo service nginx stop
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
